enableInlineBuilds: true
enableScripts: true
logFilters:
  - code: YN0007
    level: info
  - code: YN0008
    level: info
  - code: YN0013
    level: info
nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org/"
npmScopes:
  expo:
    npmRegistryServer: "https://registry.npmjs.org/"
